version: '3.8'  # Specify the Compose file version
services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile
    image: locklaan/lachlan-docker-img:latest
    container_name: lachlan-docker-container
    ports:
      - "8000:5050"
