version: '3.8' 
services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile
    image: locklaan/lachlan-docker-img:v4
    container_name: lachlan-docker-container
    ports:
      - "8000:5050"
