apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lachlan-docker-img
  template:
    metadata:
      labels:
        app: lachlan-docker-img
    spec:
      containers:
      - name: rms-container
        image: locklaan/lachlan-docker-img:v4
        ports:
        - containerPort: 5050
